# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deepdog < Formula
  desc "deepdog CLI — local agent runtime and management tool for the deepdog platform"
  homepage "https://github.com/WILLcis/deepdog"
  version "0.3.64"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WILLcis/deepdog-BIOS/releases/download/v0.3.64/deepdog-cli-0.3.64-darwin-amd64.tar.gz"
      sha256 "fc81d21c996ab7e58a173857c1f1dae8b336a14ad322687d4d146676b7b28041"

      define_method(:install) do
        bin.install "deepdog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WILLcis/deepdog-BIOS/releases/download/v0.3.64/deepdog-cli-0.3.64-darwin-arm64.tar.gz"
      sha256 "1e18a6e4467e80fd5286ac9c12444a9fd28a6936d308c42a56d8e888ba7bceda"

      define_method(:install) do
        bin.install "deepdog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WILLcis/deepdog-BIOS/releases/download/v0.3.64/deepdog-cli-0.3.64-linux-amd64.tar.gz"
      sha256 "565cd1e96861a216e0db536fe65532f3080644b51b08cac65e39cab7eec2250e"
      define_method(:install) do
        bin.install "deepdog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WILLcis/deepdog-BIOS/releases/download/v0.3.64/deepdog-cli-0.3.64-linux-arm64.tar.gz"
      sha256 "88fc4ee1eced91f23c0d4283db1f943a170e176a43ef9a70ffec0097df1e4e4c"
      define_method(:install) do
        bin.install "deepdog"
      end
    end
  end

  test do
    system "#{bin}/deepdog", "version"
  end
end
